# Используем базовый образ debian
FROM python:3.12

ENV TZ=Europe/Moscow
RUN apt-get update && apt-get install -y nano htop vim default-libmysqlclient-dev build-essential python3-mysqldb 
RUN apt-get install -y iproute2 openresolv

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем файлы зависимостей
COPY requirements.txt ./

# Устанавливаем зависимости
RUN pip3 install --no-cache-dir --upgrade pip setuptools wheel
RUN pip3 install --no-cache-dir -r requirements.txt

# Копируем остальные файлы проекта
COPY . /app/

# Запускаем бота
CMD ["python3", "bits_support.py"]
